# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fiskur.eu
email: jonathan@fiskur.eu
description: > # this means to ignore newlines until "baseurl:"
  App Developer/Team Lead. Android, Coding, Deafness, Nonsense
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fiskur.eu" # the base hostname & protocol for your site
twitter_username: jhfisher
github_username:  fiskurgit

# Build settings
markdown: kramdown
